### ISSUE TITLE
ServiceLocator - Multi-scene; Throws UnityException when recompiling while the game is running.

### ISSUE THREAD

**Issue by mathiasprisfeldt** [ArchonInteractive/SwissArmyLib#1]
1. Error
`INTERNAL_CALL_GetActiveScene is not allowed to be called from a MonoBehaviour constructor (or instance field initializer), call it in Awake or Start instead. Called from MonoBehaviour 'ManagedUpdate' on game object 'ServiceLocator - Multi-scene'.
See "Script Serialization" page in the Unity Manual for further details.
UnityEngine.SceneManagement.SceneManager:GetActiveScene()
Archon.SwissArmyLib.Utils.ServiceLocator:.cctor() (at C:/jenkins/workspace/SwissArmyLib/Archon.SwissArmyLib/Utils/ServiceLocator.cs:42)
Archon.SwissArmyLib.Events.ManagedUpdate:.cctor() (at C:/jenkins/workspace/SwissArmyLib/Archon.SwissArmyLib/Events/ManagedUpdate.cs:63)
Archon.SwissArmyLib.Events.ManagedUpdate:.cctor() (at C:/jenkins/workspace/SwissArmyLib/Archon.SwissArmyLib/Events/ManagedUpdate.cs:58)
`

2. Error
`UnityException: INTERNAL_CALL_GetActiveScene is not allowed to be called from a MonoBehaviour constructor (or instance field initializer), call it in Awake or Start instead. Called from MonoBehaviour 'ManagedUpdate' on game object 'ServiceLocator - Multi-scene'.
See "Script Serialization" page in the Unity Manual for further details.
UnityEngine.SceneManagement.SceneManager.GetActiveScene () (at C:/buildslave/unity/build/artifacts/generated/common/runtime/SceneManagerBindings.gen.cs:37)
Archon.SwissArmyLib.Utils.ServiceLocator..cctor () (at C:/jenkins/workspace/SwissArmyLib/Archon.SwissArmyLib/Utils/ServiceLocator.cs:42)
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for Archon.SwissArmyLib.Utils.ServiceLocator
Archon.SwissArmyLib.Events.ManagedUpdate..cctor () (at C:/jenkins/workspace/SwissArmyLib/Archon.SwissArmyLib/Events/ManagedUpdate.cs:58)
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for Archon.SwissArmyLib.Events.ManagedUpdate
`
### Reproduce:
1. Start the game in the editor
2. Change some code and save.
3. Wait for recompilation.

**Comment by Phault** [comment]
Supporting hot-reloading is a troublesome endeavor that I'm not convinced is worth it in the end. That said I just pushed a commit that certainly improves support for it. Can you test and see if it still occurs?
