### ISSUE TITLE
Prewarming GameObject pool doesn't disable spawned objects

### ISSUE THREAD

**Issue by FREEZX** [ArchonInteractive/SwissArmyLib#3]
As title states, if i create a GameObjectPool, and call .Prewarm on it, objects get instantiated, but they are not getting disabled. This makes the GameObjectPool with limited use for using on things such as rapid weapon firing, as the pool would need to get warmed up, and hence stutter while firing first rounds.

**Comment by Phault** [comment]
Sorry it took so long to answer you. I'm not using Unity any longer and on top of that I haven't had access to a Windows machine for quite some time.

Anyway thanks for reporting this silly mistake. It should be fixed in version 1.0.79.
